name = "i-management"
main = ".open-next/worker.js"
compatibility_date = "2026-03-21"

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://internmanagement.abdulkareem-t.workers.dev"
