name = "intern-management"
main = ".open-next/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://internmanagement.abdulkareem-t.workers.dev"
